#!/bin/sh
# Regenerate THIRD-PARTY-NOTICES whenever go.mod or go.sum changes, then commit
# the result:
#
#   bash packaging/gen-notices.sh
#
# Run it where the Go toolchain is available, for example in the packaging
# builder image:
#
#   docker run --rm -v "$PWD:/w" -w /w golang:1.26-bookworm bash packaging/gen-notices.sh
#
# debian/rules checks that the committed file still matches what this script
# produces, so an unnoticed dependency change fails the package build instead
# of shipping a binary whose license texts are wrong.
set -eu

GO=${GO:-go}
out=${1:-THIRD-PARTY-NOTICES}
line='------------------------------------------------------------------------------'

# License-ish files of a module directory: top level first, then the
# subdirectory convention some modules use.
license_files() {
	dir=$1
	for f in "$dir"/* "$dir"/LICENSES/* "$dir"/licenses/*; do
		[ -f "$f" ] || continue
		case $(basename "$f") in
			[Ll][Ii][Cc][Ee][Nn][Ss][Ee]* | [Ll][Ii][Cc][Ee][Nn][Cc][Ee]* | \
			[Cc][Oo][Pp][Yy][Ii][Nn][Gg]* | [Nn][Oo][Tt][Ii][Cc][Ee]* | \
			[Pp][Aa][Tt][Ee][Nn][Tt][Ss]* )
				printf '%s\n' "$f"
				;;
		esac
	done
	# The loop above leaves the status of the last [ -f ] test, which is false
	# for most modules; set -e in the caller would treat that as a failure.
	return 0
}

main_module=$($GO list -m)

{
	echo '=============================================================================='
	echo 'Third-party license texts'
	echo '=============================================================================='
	echo
	echo 'ssh-gate is distributed under the MIT license; see LICENSE.'
	echo
	echo 'The ssh-gate binary statically links the Go modules listed below. Each entry'
	echo 'gives the module path and version from go.mod, the license file names as'
	echo 'shipped by the module, and the full text of every such file.'
	echo
	echo 'Generated by packaging/gen-notices.sh; do not edit by hand.'
	echo
	# go list -deps prints one line per imported package, so collapse it to one
	# line per module.
	$GO list -deps -f '{{with .Module}}{{.Path}}|{{.Version}}|{{.Dir}}{{end}}' . |
		grep -v '^$' |
		awk -F'|' -v me="$main_module" '$1 != me' |
		sort -t'|' -k1,1 -u |
		while IFS='|' read -r path version dir; do
			echo "$line"
			echo "$path $version"
			echo
			files=$(license_files "$dir")
			if [ -z "$files" ]; then
				echo '  NO LICENSE FILE FOUND IN THE MODULE DIRECTORY'
				echo
				continue
			fi
			printf '%s\n' "$files" | while IFS= read -r f; do
				echo "  ${f#"$dir"/}"
			done
			echo
			printf '%s\n' "$files" | while IFS= read -r f; do
				echo "--- ${f#"$dir"/} ---"
				cat "$f"
				echo
			done
			echo
		done
} >"$out"
